version: "3.1"
name: "gs_microservices"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data\
  server:
    ports:
      - 3001:3001
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
